version: 2
jobs:
  build:
    docker:
      - image: gcc
    working_directory: /tmp/ledstrip
    steps:
      - checkout
      - run:
          name: Setup artifact folder
          command: mkdir /artifacts
      - run:
          name: cd to src dir
          command: cd /tmp/ledstrip/src
      - run:
          name: Compile the program with gcc
          command: make strip
      - run:
          name: Compile the program with arm
          command: make pi
