version: 2
jobs:
  setup:
    docker:
      - image: gcc
    steps:
      - checkout
      - run:
          name: Create needed dirs
          command: mkdir /artifacts
  build:
    docker:
      - image: gcc
    working_directory: /tmp/ledstrip
    steps:
      - checkout
      - run:
          name: Compile the program
          command: gcc -o /artifacts/hello src/main.c
workflows:
  version: 2
  build-deploy:
    jobs:
      - setup
      - build:
          requires:
            - setup