version: 2
jobs:
  build:
    docker:
      - image: gcc
    working_directory: src
    steps:
      - checkout
      - run:
          name: Compile the program
          command: gcc -o hello src/main.c