version: 2
jobs:
  build:
    docker:
      - image: gcc
    working_directory: /tmp/ledstrip
    steps:
      - checkout
      - run:
          name: Setup artifact folder
          command: mkdir /artifacts
      - run:
          name: cd to src dir
          command: cd /home/pi/ledstrip/src
      - run:
          name: Compile the program
          command: make
