version: 2
jobs:
  build:
    docker:
      - image: gcc
    working_directory: /tmp/ledstrip
    steps:
      - checkout
      - run:
          name: Compile the program
          command: gcc -o /artifacts/hello src/main.c